### ISSUE TITLE
Issue converting fast5 to BAM using fast5mod in modified base tutorial

### ISSUE THREAD

**Issue by dipannita-g** [epi2me-labs/tutorials#10]
Hi

I have been trying to use the modified base tutorial through JupyterLab for my own fast5 files  (which already have modified base information - this has been checked via HDF View). While trying to convert these fast5 to BAM files, I am getting the following error. The fast5mod package was installed and data entry was done according to the instructions in the notebook prior to this conversion.

Can you help troubleshoot this? 

Thank you.

![Capture](https://user-images.githubusercontent.com/73463877/97269309-54439700-1853-11eb-8af9-2af447f8928b.PNG)

**Comment by cjw85** [comment]
Hi @dipannita-g,

It looks like there is a typo in the command on the 5th line. There should be a `/` at the start of the output filename: so /epi2melabs... methylation.bam not epi2melabs...methylation.bam.

**Comment by dipannita-g** [comment]
Hi @cjw85 

It is still showing the same error after correcting the output file name. There is a BAM file in the output folder which is empty.

![image](https://user-images.githubusercontent.com/73463877/97272249-a1c20300-1857-11eb-8a1a-79729246b04d.png)

**Comment by cjw85** [comment]
I am running through the notebook with the sample data to check things are correct.

Can you confirm that all the input files and directories in the above exist? The original notebook has variables where you have replaced with fixed paths.

**Comment by dipannita-g** [comment]
I have uploaded the fast5 files in a folder (barcode_1_fast5) and the fasta ref in the notebook (left hand side panel, upload option and the folder/files can be seen in the first screengrab).
I copied the path and pasted it on the "Data Entry" panel in the notebook before proceeding for fast5 to BAM conversion. 
Also, when I open the folder "notebooks" in file explorer, I can see my uploaded files, so I am assuming they are correct.

**Comment by cjw85** [comment]
I have managed to replicate something approximating your issue with the sample data given with the workflow; I don't know if this is exactly your issue, only the symptom is similar. The issue I am seeing is particular to running the fast5mod program within the EPI2ME Labs environment: running the program directly on a Linux computer I don't observe the behaviour.

I will continue to investigate the issue using the sample data and report back when I understand the problem more concretely.

**Comment by dipannita-g** [comment]
Hi @cjw85!

I tried to install fast5mod package on my Windows system through WSL (Ubuntu 16.04 LTS), hoping to bypass using JupyterLab. 
But "mappy" is not getting installed.  Is it because its not a native Linux system? 

Looking forward to your response regarding running fast5mod in the Epi2MeLabs env. 

Thanks a bunch for helping me troubleshoot. 

![image](https://user-images.githubusercontent.com/73463877/97442255-a833a600-194f-11eb-8da6-0695826ab5b7.png)

**Comment by cjw85** [comment]
I believe mappy needs a C compiler to install. In you WSL shell you can run:

```sudo apt install build-essential zlib1g-dev```

This will install the GCC compiler. You can then install fast5mod with pip.

**Comment by dipannita-g** [comment]
> I believe mappy needs a C compiler to install. In you WSL shell you can run:
> 
> `sudo apt install build-essential zlib1g-dev`
> 
> This will install the GCC compiler. You can then install fast5mod with pip.

Even after installing the compiler, I am getting the same error for mappy.

**Comment by dipannita-g** [comment]
> `sudo apt install build-essential zlib1g-dev`

I am getting the same error even after installing this. 

![image](https://user-images.githubusercontent.com/73463877/97540880-44aa8680-19ea-11eb-8598-f37201a99419.png)

**Comment by cjw85** [comment]
Can you run also:

```sudo apt install python3-dev```

This will correct the "Python.h: No such file or directory" error

**Comment by dipannita-g** [comment]
Hi @cjw85 

When I try to run the fast5mod program directly through WSL, I get the following error:

>fast5mod: error: unrecognized arguments: /home/vperumal/MRSA.fasta

This is the Reference input. I have tried to change the path and I still get the same error regardless. 
Then I tried just putting the path names given in the demo instructions, and I still get the same error. 

![image](https://user-images.githubusercontent.com/73463877/97860339-f964e080-1d27-11eb-9153-5025734c07c6.png)

**Comment by cjw85** [comment]
The error message indicates that you have missed listing `guppy2sam` in your command line arguments.

**Comment by dipannita-g** [comment]
I copy pasted the commands from https://github.com/nanoporetech/fast5mod
![image](https://user-images.githubusercontent.com/73463877/97862015-ab051100-1d2a-11eb-80d1-b10b5cca13ab.png)

**Comment by cjw85** [comment]
The command you need is

    fast5mod guppy2sam ${FAST5} --reference ${REFERENCE} ....

i.e. with `--reference` between `${FAST5}` and `${REFERENCE}`. This was omitted from the README, which I have now corrected.

**Comment by dipannita-g** [comment]
Thanks for the command. When I run this now, I am getting another error:
>BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

![image](https://user-images.githubusercontent.com/73463877/97865582-72683600-1d30-11eb-8576-e22c759337a9.png)

**Comment by cjw85** [comment]
I think you may be back to something similar to you original problem. Is it possible for you to share your input files for me to use to debugging?

I will move this issue to the fast5mod project as it does not appear to be a problem with the EPI2MELabs tutorial per se.

**Comment by dipannita-g** [comment]
Hi @cjw85. 
Sure. Please share your email so that I can send my files.

**Comment by dipannita-g** [comment]
> I think you may be back to something similar to you original problem. Is it possible for you to share your input files for me to use to debugging?

Here is the Google Drive link to the files:
https://drive.google.com/drive/folders/1jBW-0RBY6KqY576ObyILVY6iOYZfSRA6?usp=sharing

**Comment by cjw85** [comment]
Apologies,
I have downloaded your data dn will take a look in due course.

**Comment by cjw85** [comment]
I believe your latest issue is due to the version of samtools that you are using. Can you modify the command you are running to contain:

```| samtools sort -b -@ 8 - > out.bam```

note the `-`  before the `>`. Your files are processed correctly for me with this amendment and older versions of samtools.

**Comment by dipannita-g** [comment]
Hi @cjw85 
> | samtools sort -b -@ 8 - > out.bam

-b is not a option for "sort" function in samtools. 

> note the `-` before the `>`. Your files are processed correctly for me with this amendment and older versions of samtools.

This does not correct the broken pipe error still. 

![image](https://user-images.githubusercontent.com/73463877/98667246-2b072880-2374-11eb-933b-a2eb0dc75be8.png)

**Comment by cjw85** [comment]
The broken pipe error results from errors in the samtools commands. Can I suggest you try the following: first run `fast5mod guppy2sam` without piping the data through samtools, so first directly outputting a SAM file:

```
FAST5PATH=/home/vperumal/Barcode_1_fast5
REFERENCE=/home/vperumal/MRSA.fasta
OUTBAM=meth.bam
fast5mod guppy2sam ${FAST5PATH} --reference ${REFERENCE} \
    --workers 74 --recursive > fast5mod.sam
```

This output can be sorted and converted to bam using samtools. You should refer to the help messages for your version of samtools to understand best how to do this.

**Comment by dipannita-g** [comment]
> FAST5PATH=/home/vperumal/Barcode_1_fast5
> REFERENCE=/home/vperumal/MRSA.fasta
> OUTBAM=meth.bam
> fast5mod guppy2sam ${FAST5PATH} --reference ${REFERENCE} \
>     --workers 74 --recursive > fast5mod.sam

I was able to get the sam file using this, which I processed further to get a sorted .bam file using my version of the samtools. Thanks for the help!

**Comment by dipannita-g** [comment]
FAST5PATH=/home/vperumal/Barcode_1_fast5
REFERENCE=/home/vperumal/MRSA.fasta
OUTBAM=meth.bam
fast5mod guppy2sam ${FAST5PATH} --reference ${REFERENCE}
--workers 74 --recursive > fast5mod.sam

I was able to get the sam file using this, which I processed further to get a sorted .bam file using my version of the samtools. Thanks for the help!
