### ISSUE TITLE
Differential gene expression TPM or NumReads

### ISSUE THREAD

**Issue by callumparr** [epi2me-labs/tutorials#17]
When it merges counts from the `.sf` outputs from `salmon` for each sample does it take the `TPM` counts or `NumRead` conuts?

**Comment by sagrudd** [comment]
Hei Callum - thanks for the question!

The EPI2ME Labs differential gene expression tutorial provides a walk-through of the https://github.com/nanoporetech/pipeline-transcriptome-de workflow. In the project's Snakefile ( https://github.com/nanoporetech/pipeline-transcriptome-de/blob/master/Snakefile ) we can see that the Salmon analysis is performed by the rule "rule count_reads" and the results are parsed by the rule "rule merge_counts:" with a script called merge_count_tsvs.py ( https://github.com/nanoporetech/pipeline-transcriptome-de/blob/master/scripts/merge_count_tsvs.py ) 

The comment on the last commit suggests that while in the past we may have used TPM, we are now using the number of reads. This can be confirmed by having a look at the merge_count_tsvs.py script where the NumReads column from quant.sf is renamed to Count before the values are aggregated into a single monolithic TSV file.

**Comment by callumparr** [comment]
Hey thanks so much for the quick and detailed reply.
