### ISSUE TITLE
request: nextflow

### ISSUE THREAD

**Issue by PWSmit** [epi2me-labs/tutorials#22]
Hi, 
Ideally, you would be able to run workflows (i.e. wf-artic) from within epi2melabs jupyter notebooks to simplify and standardise all epi2me labs or ONTresearch processes. If I am not mistaken, nextflow is not installed and would not work while snakemake can be done (given earlier versions of ontresearch/artic). 

could you add nextflow and workflows to epi2melabs-notebooks? 

thanks! 
Pieter

**Comment by cjw85** [comment]
Hi Pieter,

We have have something in the pipeline 😉 that will allow running of our Nextflow workflows incorporated into the Jupyter environment.

**Comment by cjw85** [comment]
Our recent release of EPI2ME Labs has the ability to run workflows from inside the JupyterLab environment, though not directly from within notebooks (this is not an angle we are likely to persue).

**Comment by PWSmit** [comment]
Cool, thanks! Ok so not via a notebook but how should I do it then? Any information would be appreciated :) 

Thanks, 
Pieter

**Comment by cjw85** [comment]
We have an article describing the new interface here:
https://labs.epi2me.io/jupyterflow/

Once Nextflow has run the results are available to view within Jupyter, and can be manipulated with a notebook if desired. We are likely to move many of the existing notebooks to be extensions of Nextflow workflows: showing how the standard outputs should be interpreted and manipulated.
