### ISSUE TITLE
Bokeh/aplanat plots not showing

### ISSUE THREAD

**Issue by paulauitt2** [epi2me-labs/tutorials#23]
Hi,

I'm trying to do the tutorials in EPI2ME Labs launcher, just with the sample data, however, I tried a few different notebooks (EPI2ME Labs tutorial, Cas9, basic QC) and in all of them bokeh/aplanat plots are not showing, both inline and in the report. Someone has any idea how to solve this?

Paula

**Comment by nrhorner** [comment]
Hi Paula,

I'm sorry that you are having issues with the notebooks. I'm looking into now.

Neil

**Comment by nrhorner** [comment]
Hi Paula,

We have released a new version of Labs Launcher that includes updates that should fix your problem.  

In the Launcher, click `Restart` and then `Update` to get the latest version.  `Server Version: v1.1.11` should then be displayed in the bottom right corner. 

Please let us know if this does not fix your problem.

Neil
