### ISSUE TITLE
Unable to generate CSV for EPI2ME 16S analysys

### ISSUE THREAD

**Issue by checcomugna** [epi2me-labs/tutorials#24]
Hello,
I'm trying to run the "Analysis_of_EPI2ME_16S_CSV_Output" script. I'm new in te Python language, thus excuse me in advance..
I downloaded the CSV from Epi2Me obtained from a 16S run with SQK-16S024 barcode kit.
I can't generate an update file from the "Data Entry" section: I choose my CSV as input, and specify a desired output file, but nothing happens..
In addition, running the next command from "Analysis" section, I have the following error:
`NameError: name 'parse_epi2me' is not defined`
I tried to specify the full path of my input file (with "") and the CSV file alone, but the error is still there.
I encounter this same last error if I choose the "Use sample data" option from the "Data Entry".

Can you help me please? I'm stuck with my analyses and my research
Thank you in advance
Francesco

**Comment by nrhorner** [comment]
Hi Francesca,

For your second issue: `NameError: name 'parse_epi2me' is not defined`, can you ensure that you have ran the previous code blocks prior to running. 


![image](https://user-images.githubusercontent.com/4233686/156189128-f1e8a7d1-8f90-4724-918d-b30dc59ddd68.png)
