### ISSUE TITLE
How to cite your HG002 public data? 

### ISSUE THREAD

**Issue by hmyh1202** [epi2me-labs/tutorials#26]
Hi，

  How to cite your data of gm24385_mod_2021.09 in my paper ?

Thank you !

**Comment by cjw85** [comment]
Hi @hmyh1202,

I have created a Zenodo record here: https://zenodo.org/record/6372330#.YjhFVPXP2Ak

**Comment by hmyh1202** [comment]
ok, fine.

If the data of RRBS_methylated_control and RRBS_unmethylated_control spike-in DNA were absolutely methylated and unmethylated? Did you have do some check and test ?

Thank you.

**Comment by cjw85** [comment]
The bisulfite sequencing outsourced to a service provider, this is what they reported to us:

>Methylated and unmethylated spike-in sequences are included in the libraries in order to check the BS conversion rate. We expect the conversion rate of the methylated spike-ins to be lower than 2% and of the unmethylated spike-ins to be over 99%. For your project, it was respectively, 1.5% an 99.6%.
Note that some specific and known cytosines in the methylated spike-ins are unmethylated and should not be taken into account for calculating the conversion rate.

**Comment by hmyh1202** [comment]
Got it, thank u.

**Comment by hmyh1202** [comment]
Hello:
@cjw85 

What`s the meaning the each column of the  bonito.cpg.bed.gz file ?

chr1    10468   10469   5mC     904     +       10468   10469   0,0,0   115     79.81   21      83      10
chr1    10469   10470   5mC     880     -       10469   10470   0,0,0   126     88.29   13      98      3
chr1    10470   10471   5mC     913     +       10470   10471   0,0,0   115     87.62   13      92      8
chr1    10471   10472   5mC     873     -       10471   10472   0,0,0   126     82.73   19      91      4
chr1    10483   10484   5mC     830     +       10483   10484   0,0,0   118     87.76   12      86      14

Thank you !

**Comment by cjw85** [comment]
That information is available here:

https://github.com/epi2me-labs/modbam2bed#method-and-output-format
