### ISSUE TITLE
Differential Gene expression 

### ISSUE THREAD

**Issue by gggjerry** [epi2me-labs/tutorials#30]
Hii,

I ran into the problem of not being able to find snakemake at the step of alignment, despite running all the code from the top. 
![Screenshot 2022-09-04 at 09 52 47](https://user-images.githubusercontent.com/83358320/188293785-692b01c6-a625-497f-a7ac-851b31a603f1.png)

What can I do? 
Many thanks.

**Comment by cjw85** [comment]
Hi @gggjerry,

We no longer recommend using the Differential Expression tutorial, it will be removed from a subsequent version of EPI2ME Labs. Instead you may use the wf-transcriptomes workflow, which includes a Differential Expression option.

**Comment by gggjerry** [comment]
Dear Sir, 

Thanks for the kind suggestions.
